### ISSUE TITLE
(URGENT) Relaton CalConnect crashing on updated standards.calconnect.org

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-calconnect#6]
https://github.com/CalConnect/csd-directive-standardization-publication/runs/775474511?check_suite_focus=true

```
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
130
[relaton-calconnect] ("CC/DIR 10002") fetching...
131
bundler: failed to load command: metanorma (/usr/local/bundle/bin/metanorma)
132
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 546 column 430
133
  /usr/local/lib/ruby/2.6.0/psych.rb:456:in `parse'
134
  /usr/local/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
135
  /usr/local/lib/ruby/2.6.0/psych.rb:390:in `parse'
136
```

**Comment by andrew2net** [comment]
The endpoint https://standards.calconnect.org/relaton/index.yaml used to return data in YAML format, but now it returns data in XML format. Was it done by purpose?

**Comment by ronaldtse** [comment]
@andrew2net not by purpose 😉

**Comment by andrew2net** [comment]
Fixed. Please use relaton-cli v 1.1.3
